# .bash_aliases
#
# by Bruno S. Vezzaro
#
# UPDATED 2010-01-22 at 08:34

alias grep='grep --color' # show differences in colour
alias g='grep -i --color'
alias p='ps x'
alias o='less'
alias ls='ls -Atr --color=auto'
alias l='ls -lh'
alias cd..='cd ..'
alias cd-='cd -'
alias ..='cd ../'
alias ...='cd ../../'
alias md='mkdir -p'
alias mkdir='mkdir -p'
alias rd='rm -R'
alias rm='rm -f'
alias mv='mv -v'
alias m='mount'
alias um='umount'
alias du='du -hc'
alias df='df -h'
alias fl='file'
#alias s='ssh'
alias S='screen -ex'
alias T='tmux'
alias x='startx'
alias v='vim'
alias free='free -m'
#alias my_ip='wget -O - checkip.dyndns.org 2>/dev/null|cut -d ":" -f2|cut -d "<" -f1'
alias hex='hexedit'
#alias mpg='mpg123'
#alias mpgd='\ls|sort|mpg123 -v -@ -'
#alias cls='clear'
#alias dpl='display'
alias shut='shutdown -h now'
#alias el='elvis'
#alias gns3='/usr/local/GNS3-0.7RC1-src/./gns3'
alias freechess='xboard -ics -icshost 69.36.243.188'
alias ofc='/usr/bin/openoffice.org'
alias md5='md5sum'
#alias rdesktop-cpf='rdesktop -u Administrador -k pt-br -g 80% -x m -a 8 -z -P -r disk:slackr=/home/bruno 189.19.252.23:3390'
#alias rdesktop-win='rdesktop -u bruno -p bruno123 -k pt-br -g 90% -z -P -r disk:slackr=/home/bruno 192.168.1.3'
#alias rdesktop-samara='rdesktop -u Administrador -p ibmcpf -k pt-br -g 90% -z -P -r disk:slackr=/home/bruno 192.168.1.20'
alias pdf2txt='pdftotext -enc Latin1 -layout'
alias pdf='xpdf'
#alias pyh='splitvt -rcfile ~/.splitvtrc-pyhelp'
#alias dynamips='/usr/bin/dynamips-0.2.8-RC2-x86.bin 2>&1 > /dev/null'
#alias vortex2='rdesktop vortex2.adm.intranet -k pt-br -g80% -u uoladmin -p sun123'
#alias base25='rdesktop base25.adm.intranet -k pt-br -g80% -u uoladmin -p sun123'
#alias tariq1='rdesktop tariq1.adm.intranet -k pt-br -g90% -r disk:disco=/home/silvez -u bvezzaro'
#alias vortex2='rdesktop vortex2.adm.intranet -k pt-br -g80% -u uoladmin -p sun123'
alias quark5='rdesktop quark5.adm.intranet -k pt-br -g80% -u uoladmin -p rebsguin69'
#alias tariq='\rm -f ~/.rdesktop/*; rdesktop a2-tariq1.uolcorp.intranet -k pt-br -g90% -r disk:disco=/home/silvez -u "uolcorp\bvezzaro"'
alias tariq='\rm -f ~/.rdesktop/*; rdesktop a2-tariq1.uolcorp.intranet -k pt-br -g 1366x768 -r disk:disco=/home/silvez -u "uolcorp\bvezzaro"'
alias raiden='rdesktop a1-raiden1 -k pt-br -g80% -0 -u uoladmin -p sun123 -r disk:disco=/'
#alias rdesk='rdesktop -k pt-br -g80% -0 -u uoladmin -p sun123 -r disk:disco=/'
alias rdesk='rdesktop -k pt-br -g 1366x768 -0 -u uoladmin -p sun123 -r disk:disco=/'
alias winxp='/usr/bin/VBoxManage startvm winxp'
alias cl='curl -k -A "Mozilla/5.0"'
alias ob='cat ~/oneliners-bash.txt'
alias w3='w3m -o user_agent="Mozilla/5.0" -o ssl_verify_server="no"'
alias hst='history|tail -n 30'
#
